"""initial baseline

Revision ID: 0aa9409a2368
Revises: 
Create Date: 2026-04-20 15:47:53.835604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa9409a2368'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cached_purchase_order_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_summary_no_of_neto_orders'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'retail'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'retail'"))

    with op.batch_alter_table('cached_purchase_order_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_summary_no_of_neto_orders'), ['no_of_neto_orders'], unique=False)

    # ### end Alembic commands ###
